import { Inter, Prompt } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const prompt = Prompt({
  weight: ['300', '400', '500', '700'],
  subsets: ["thai", "latin"],
  variable: '--font-prompt',
});

export const metadata = {
  title: "Election 69",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${prompt.variable}`}>{children}</body>
    </html>
  );
}
